# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: banking.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'banking.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rbanking.proto\x12\x07\x62\x61nking\"$\n\x11GetBalanceRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"O\n\x14UpdateBalanceRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x01\x12\x16\n\x0etransaction_id\x18\x03 \x01(\t\"3\n\x0f\x42\x61lanceResponse\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0f\n\x07\x62\x61lance\x18\x02 \x01(\x01\"E\n\x0fTransferRequest\x12\x11\n\tfrom_user\x18\x01 \x01(\t\x12\x0f\n\x07to_user\x18\x02 \x01(\t\x12\x0e\n\x06\x61mount\x18\x03 \x01(\x01\"\xc3\x01\n\x10TransferResponse\x12\x38\n\x06status\x18\x01 \x01(\x0e\x32(.banking.TransferResponse.TransferStatus\x12\x16\n\x0etransaction_id\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\t\"J\n\x0eTransferStatus\x12\x0b\n\x07SUCCESS\x10\x00\x12\x16\n\x12INSUFFICIENT_FUNDS\x10\x01\x12\x13\n\x0fINVALID_ACCOUNT\x10\x02\"!\n\x0eHistoryRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"d\n\x11TransactionRecord\x12\x16\n\x0etransaction_id\x18\x01 \x01(\t\x12\x14\n\x0c\x63ounterparty\x18\x02 \x01(\t\x12\x0e\n\x06\x61mount\x18\x03 \x01(\x01\x12\x11\n\ttimestamp\x18\x04 \x01(\t\"C\n\x0fHistoryResponse\x12\x30\n\x0ctransactions\x18\x01 \x03(\x0b\x32\x1a.banking.TransactionRecord2\xa5\x01\n\x11\x41\x63\x63ountManagement\x12\x44\n\nGetBalance\x12\x1a.banking.GetBalanceRequest\x1a\x18.banking.BalanceResponse\"\x00\x12J\n\rUpdateBalance\x12\x1d.banking.UpdateBalanceRequest\x1a\x18.banking.BalanceResponse\"\x00\x32\xa6\x01\n\x0bTransaction\x12I\n\x10InitiateTransfer\x12\x18.banking.TransferRequest\x1a\x19.banking.TransferResponse\"\x00\x12L\n\x15GetTransactionHistory\x12\x17.banking.HistoryRequest\x1a\x18.banking.HistoryResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'banking_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETBALANCEREQUEST']._serialized_start=26
  _globals['_GETBALANCEREQUEST']._serialized_end=62
  _globals['_UPDATEBALANCEREQUEST']._serialized_start=64
  _globals['_UPDATEBALANCEREQUEST']._serialized_end=143
  _globals['_BALANCERESPONSE']._serialized_start=145
  _globals['_BALANCERESPONSE']._serialized_end=196
  _globals['_TRANSFERREQUEST']._serialized_start=198
  _globals['_TRANSFERREQUEST']._serialized_end=267
  _globals['_TRANSFERRESPONSE']._serialized_start=270
  _globals['_TRANSFERRESPONSE']._serialized_end=465
  _globals['_TRANSFERRESPONSE_TRANSFERSTATUS']._serialized_start=391
  _globals['_TRANSFERRESPONSE_TRANSFERSTATUS']._serialized_end=465
  _globals['_HISTORYREQUEST']._serialized_start=467
  _globals['_HISTORYREQUEST']._serialized_end=500
  _globals['_TRANSACTIONRECORD']._serialized_start=502
  _globals['_TRANSACTIONRECORD']._serialized_end=602
  _globals['_HISTORYRESPONSE']._serialized_start=604
  _globals['_HISTORYRESPONSE']._serialized_end=671
  _globals['_ACCOUNTMANAGEMENT']._serialized_start=674
  _globals['_ACCOUNTMANAGEMENT']._serialized_end=839
  _globals['_TRANSACTION']._serialized_start=842
  _globals['_TRANSACTION']._serialized_end=1008
# @@protoc_insertion_point(module_scope)
